### PR TITLE
Remove multiple codegens on UI startup

### PR DESCRIPTION
**Pull request by blrubenstein**
We had previously been running our swagger codegen three times on startup, once in the ruby script, and then once on each of `npm start` and `npm test`. This fixes that issue.

### CODE REVIEW

**Comment by markfickett** [comment]
Should we kill the `npm start` and `npm test` entries in `package.json`?

I don't quite understand where the duplication came from, but I want to make sure we consistently use the same command to run/test the UI, and that we do always swagger-codegen when we need to.

It looks like now we don't run codegen at all when the UI docker container starts up, is that true?

**Comment by blrubenstein** [comment]
We need to do the `npm start` and `npm test` commands for circle. 

We do run codegen, we just explicitly run the ruby script `swagger_regen()` in devstart.rb.

**Comment by johnstill** [comment]
@markfickett `project.rb dev-up` runs swagger-regen prior to docker doing anything; that's why we don't need to in a docker entrypoint.

**Comment by markfickett** [comment]
OK -- I think it would be clearest if swagger-regen only ever happened automatically from the one level (probably Ruby scripts), and then everywhere else we used the `npm` commands, just to have fewer options in flight. But it sounds like this will WAI, so I'm OK with it if you just want to do this.

**Pull request merged**
