### PR TITLE
[RW-6086][risk=no] Add cdrVersion field to rdr push

### PR DESCRIPTION
**Pull request by petesantos**
Description:

Add the CDR version name to the nightly RDR push
Testing: Manually verified that the new field is present and has a reasonable value
No novel functionality or changes to the inherent design were made, existing tests should already cover this code.

---
**PR checklist**

- [x] This PR meets the Acceptance Criteria in the JIRA story
- [ ] The JIRA story has been moved to Dev Review
- [x] This PR includes appropriate unit tests
- [x] I have run and tested this change locally
- [ ] I have run the E2E tests on ths change against my local UI and/or API server with `yarn test-local` or [yarn test-local-devup](https://github.com/all-of-us/workbench/blob/master/e2e/README.md#examples)
- [ ] If this includes a UI change, I have taken screen recordings or screenshots of the new behavior and notified the PO and UX designer
- [x] If this includes an API change, I have updated the appropriate Swagger definitions and notified API consumers
- [ ] If this includes a new feature flag, I have created and linked new JIRA tickets to (a) turn on the feature flag and (b) remove it later

### CODE REVIEW

**Review by dmohs — APPROVED** [review]
Verified presence of new field and value.

**Review by calbach — COMMENTED** [review]
It's probably worth adding  cdr version to this test, by my reading it doesn't currently cover this: https://github.com/all-of-us/workbench/blob/aa2d8f6d8b0457b625381239eeac714418c67315/api/src/test/java/org/pmiops/workbench/rdr/RdrExportServiceImplTest.java

**Comment by dmohs** [comment]
@calbach I think this test covers this case:
https://github.com/all-of-us/workbench/blob/aa2d8f6d8b0457b625381239eeac714418c67315/api/src/test/java/org/pmiops/workbench/rdr/RdrExportServiceImplTest.java#L194

From my reading, that test ensures that some of the fields are present when converting from a `DbWorkspace` into an `RdrWorkspace`. Testing for this specific field would just ensure that there isn't logic in the mapping library that treats a field called "cdrVersionName" differently than other fields, but I think that is a low-enough probability that testing for it would cause more noise than signal. Does that logic sound right to you?

**Review by calbach — APPROVED** [review]
Thanks, you're right that this would add no additional value - the test basically mocks out everything including the mapper, so it's barely covering anything. My general concern around this specific field is that it's pulling from a foreign relationship, which is slightly different than most of the existing cases, but that won't be addressed by extending the current test model.

[Our Mapstruct guidelines recommend testing mappers](https://github.com/all-of-us/workbench/blob/b6fe9bc769df00ce5106ca780727f212168c7d34/api/docs/mapstruct.md#write-tests-for-mappers), which we don't have for `RdrMapper`, and would have covered this concern. This might be a nice easy test to include in this PR (there are tons of examples, see file suffix `MapperTest.java`), but I won't block as it is an existing omission and this PR doesn't create significant additional risk.

**Comment by dmohs** [comment]
@calbach Yes! Implied in my note is an assumption that the existing tests are adequate, which should mean that checking for the new field would not add value. Backfilling the missing test makes sense, but I do think that should be treated as a separate task rather than part of this change. @petesantos Would you please take the task of creating that story?

**Comment by petesantos** [comment]
Added RW-6344

**Pull request merged**
