### PR TITLE
[RW-11086][risk=no] Adding Java test coverage reports to build artifacts.

### PR DESCRIPTION
**Pull request by evrii**
Adding Jacoco reports to our build/reports directory.

---
**PR checklist**

- [x] I have included an issue ID or "no ticket" in the PR title as outlined in [CONTRIBUTING.md](https://github.com/all-of-us/workbench/blob/main/.github/CONTRIBUTING.md).
- [x] I have included a risk tag of the form `[risk=no|low|moderate|severe]` in the PR title as outlined in [CONTRIBUTING.md](https://github.com/all-of-us/workbench/blob/main/.github/CONTRIBUTING.md).
- [ ] I have manually tested this change and my testing process is described above.
- [ ] This change includes appropriate automated tests, and I have documented any behavior that cannot be tested with code.
- [ ] I have added explanatory comments where the logic is not obvious.
- One or more of the following is true:
  - [ ] This change is intended to complete a JIRA story, so I have checked that all AC are met for that story.
  - [ ] This change fixes a bug, so I have ensured the steps to reproduce are in the Jira ticket or provided above.
  - [ ] This change impacts deployment safety (e.g. removing/altering APIs which are in use), so I have documented the impacts in the description.
  - [ ] This change includes a new feature flag, so I have created and linked new JIRA tickets to (a) turn on the feature flag and (b) remove it later.
  - [ ] This change modifies the UI, so I have taken screenshots or recordings of the new behavior and notified the PO and UX designer in [Slack](https://pmi-engteam.slack.com/archives/C02MWP2RN5P).
  - [ ] This change modifies API behavior, so I have run the relevant E2E tests locally because API changes are not covered by our PR checks.
  - [ ] None of the above apply to this change.

### CODE REVIEW

**Review by yonghaoy — COMMENTED** [review]
Does it work? Where can we see coverage report? Can we see that in CircleCi or github?
Also we need to customize things like enable html, html destination?

**Comment by evrii** [comment]
> Does it work? Where can we see coverage report? Can we see that in CircleCi or github? Also we need to customize things like enable html, html destination?

It does, the results can be seen in [the artifacts section of CircleCI](https://output.circle-artifacts.com/output/job/d20fd820-0b6b-489f-9062-8fc05656f46b/artifacts/0/JunitTestResult/jacoco/test/html/index.html). There are approaches to make this more readable. I would like to upload the reports to Codacy to get some of its processing functionality and GitHub integrations, but our connection to Codacy has been broken for a while now. I am hoping to look into that as a separate effort.

**Comment by yonghaoy** [comment]
> > Does it work? Where can we see coverage report? Can we see that in CircleCi or github? Also we need to customize things like enable html, html destination?
> 
> It does, the results can be seen in [the artifacts section of CircleCI](https://output.circle-artifacts.com/output/job/d20fd820-0b6b-489f-9062-8fc05656f46b/artifacts/0/JunitTestResult/jacoco/test/html/index.html). There are approaches to make this more readable. I would like to upload the reports to Codacy to get some of its processing functionality and GitHub integrations, but our connection to Codacy has been broken for a while now. I am hoping to look into that as a separate effort.

This looks awesome! Thanks

**Review by Qi77Qi — APPROVED** [review]
thanks for looking into this!

**Comment by Peter-Lavigne** [comment]
This is great!

**Comment by Peter-Lavigne** [comment]
I'm a fan of the visual indicators of which branches aren't covered, it makes it easy to grok coverage quality, too. 
image

**Pull request merged**
