### PR TITLE
Change to workspace response.

### PR DESCRIPTION
**Pull request by blrubenstein**
The goal is to send along some other information with getWorkspace, that we get for free from FC, such as the current user's access level to the workspace.

I'm starting with the simplest possible piece as a building block for adding actual access controls.

### CODE REVIEW

**Comment by calbach** [comment]
Why not put these fields onto `Workspace`? The standard REST semantics I'm used to involve directly returning the resource you're getting.

Following on this point - would we want to return this information from other Workspace endpoints? e.g. `List` (or query - I forge what it's called)?

**Comment by danqrodney** [comment]
+1. Let's change Workspace to have this info.

**Comment by dmohs** [comment]
Hm... These seem like they might be semantically two different things. I see the Workspace object as containing properties about the workspace. The current user's access level depends on who is asking. If this understanding is correct, my preference would be to separate them—keep things that are semantically different physically separated.

**Comment by blrubenstein** [comment]
I put these fields separate from `Workspace` in part because that lines up with the implementation of FC's API. I do agree with @dmohs that I would like the workspace to look the same as an object no matter who is calling it.

Re: `List` and `Update`, I agree that it would be good if those had this info as well. Part of why I did this here is that we get the current user's access level for free from FC with the getWorkspace, and we will get it for free from `List` at least, when we implement using FC's `listWorkspaces`. However, that's blocked on filtering by tags for now, and we have less of a need to pull that information for list, except for display on the status column in the workspace list view.

**Comment by calbach** [comment]
Thanks - I missed that subtlety. Definitely agree the workspace model should not change depending on who's calling.

If they are going to be separate, then a separate endpoint might be appropriate - maybe this is what you meant @dmohs. I think returning both of these from GetWorkspace would be messy, but acceptable if we see the purpose of the workbench API as primarily fitting to the exact needs of the UI. If it's meant to be a standalone API then splitting it out as another endpoint would be cleaner in my opinion (I don't have enough background on the design principles for the API).

**Comment by danqrodney** [comment]
OK. I'm fine with keeping the resources separate. (I don't think it's strictly necessary, but it does have some nice properties... like the client shouldn't try to set these fields, so a PUT for a workspace doesn't have to accept them.)

I don't think we need separate endpoints for retrieving just workspaces from these things... but I do think getWorkspace and listWorkspaces ought to return the same type, though.

**Comment by blrubenstein** [comment]
Agreed that getWorkspace and listWorkspaces should return the same type. Do you want me to put in a temporary thing to call to FC to fetch the accessLevels in list? (Will need to be one call per workspace for now, because we can't use their list endpoint for this)

**Comment by danqrodney** [comment]
We have our own data on access levels in the DB. If their list API won't return this, we should use the data from our DB and ask them to add it. (Making N calls to FC is not good.)

**Comment by blrubenstein** [comment]
Got it. We can do a search through on our data for now, and I'll throw a todo on to use their list API.

Their list API does return this information, however, it doesn't filter by AoU workspaces yet, so when that is implemented then we can move to that.

**Comment by danqrodney** [comment]
OK. We *can* (FWIW) use their list API and do our own filtering in memory... not sure if we want to go there now. It would be good to confirm that filtering by tags is somewhere on their roadmap soon.

**Comment by blrubenstein** [comment]
PTAL: I had to jump through some hoops to do the getWorkspaces change, but it works. The one thing I'm not sure about is getWorkspacesForReview doesn't use WorkspaceResponse, since it doesn't want and shouldn't depend on access level. I'm not sure it will even end up pulling the FC data. Thus is why we still have `WorkspaceListResponse` and why I ended up naming the getWorkspaces response `WorkspaceResponseListResponse`.

**Comment by calbach** [comment]
For future reference, here is the standard REST method style that I prefer to follow where possible (and I think the Broad's recommended API style guide as well): https://cloud.google.com/apis/design/standard_methods#get

Deviating from standard REST in too many places will make for an inconsistent (and less composable) API, but understood that if we're primarily catering to a UI, practically speaking we may need to lump common actions together like this to avoid unnecessary XHRs.

**Comment by danqrodney** [comment]
FWIW: an alternative to this PR would be to return the ACL on each workspace and have the client work out the access level of each workspace based on the identity of the logged in user. (Technically we don't really need to say the access level of each workspace in a separate resource, if we have the full ACL available.)

I don't mind this, either, though.

**Comment by dmohs** [comment]
Thanks for the pointer, CH. I added an item to our tech talk slot to discuss REST API style. I think this would be an illustrative example to discuss the pros and cons and how it maps to that recommendation.

**Pull request merged**
