### PR TITLE
[RW-6272][risk=no][Spring 2 Upgrade Step 2] explicitly enable Bean overriding

### PR DESCRIPTION
**Pull request by yonghaoy**
Description:
Since Spring 1, Bean Overriding will be disabled by default. To prepare Spring 2 upgrade, explicitly set it beforehand. 
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes

Why:
In BQTest, IntegrationTest, and UniTest, those all tests, and we want to override some beans like MockBean, Clock, FakeApiClients.  And I think that is the common case that allow test to override main server's beans for testing purpose.

For tools, there are some duplicated bean names, and I think we need to use tools bean for them, not main app's bean. 

---
**PR checklist**

- [ ] This PR meets the Acceptance Criteria in the JIRA story
- [ ] The JIRA story has been moved to Dev Review
- [ ] This PR includes appropriate unit tests
- [ ] I have run and tested this change locally
- [ ] I have run the E2E tests on ths change against my local UI and/or API server with `yarn test-local` or [yarn test-local-devup](https://github.com/all-of-us/workbench/blob/master/e2e/README.md#examples)
- [ ] If this includes a UI change, I have taken screen recordings or screenshots of the new behavior and notified the PO and UX designer
- [ ] If this includes an API change, I have updated the appropriate Swagger definitions and notified API consumers
- [ ] If this includes a new feature flag, I have created and linked new JIRA tickets to (a) turn on the feature flag and (b) remove it later

### CODE REVIEW

**Review by jmthibault79 — APPROVED** [review]
looks fine, but I am unfamiliar with the implications here.  Is there a reason we might want to prevent overrides?

**Comment by yonghaoy** [comment]
> looks fine, but I am unfamiliar with the implications here. Is there a reason we might want to prevent overrides?

Actually all parts I am changing is to allow override. 
In BQTest, IntegrationTest, and UniTest, those all tests, and we want to override some beans like MockBean, Clock, FakeApiClients.  And I think that is the common case that allow test to override main server's beans for testing purpose.

For tools, there are some duplicated bean names, and I think we need to use tools bean for them, not main app's bean.

**Comment by jmthibault79** [comment]
OK, thanks.  Since this is something we use a lot we should certainly enable it.

I was curious what the motivation was for Spring to disable it by default

**Review by calbach — APPROVED** [review]
Great that we can split this part out. In tests, providing duplicate beans like this is almost never intentional - in fact we had a case where this caused confusion / errors earlier this week on Pete's testing PR. After we do the migration, I think it's worth having a ticket to explore turning this back on (i.e. remove the override, go back to spring2's default).

The only quasi-legitimate use I'm aware of currently is in the tools, but there may be better patterns for that in spring2 - I don't love the current solution. In tests, it should rarely be expected that we're duplicating beans because the standard definitions are not imported.

**Comment by yonghaoy** [comment]
> Great that we can split this part out. In tests, providing duplicate beans like this is almost never intentional - in fact we had a case where this caused confusion / errors earlier this week on Pete's testing PR. After we do the migration, I think it's worth having a ticket to explore turning this back on (i.e. remove the override, go back to spring2's default).
> 
> The only quasi-legitimate use I'm aware of currently is in the tools, but there may be better patterns for that in spring2 - I don't love the current solution. In tests, it should rarely be expected that we're duplicating beans because the standard definitions are not imported.

Actually I think overriding bean is somehow needed in Test.  For example, without this, I got BeanOverrideException for the clock bean:
https://github.com/all-of-us/workbench/blob/master/api/src/test/java/org/pmiops/workbench/SpringTest.java#L20
And also https://github.com/all-of-us/workbench/blob/master/api/src/integration/java/org/pmiops/workbench/IntegrationTestConfig.java#L18

**Comment by yonghaoy** [comment]
> > Great that we can split this part out. In tests, providing duplicate beans like this is almost never intentional - in fact we had a case where this caused confusion / errors earlier this week on Pete's testing PR. After we do the migration, I think it's worth having a ticket to explore turning this back on (i.e. remove the override, go back to spring2's default).
> > The only quasi-legitimate use I'm aware of currently is in the tools, but there may be better patterns for that in spring2 - I don't love the current solution. In tests, it should rarely be expected that we're duplicating beans because the standard definitions are not imported.
> 
> Actually I think overriding bean is somehow needed in Test. For example, without this, I got BeanOverrideException for the clock bean:
> https://github.com/all-of-us/workbench/blob/master/api/src/test/java/org/pmiops/workbench/SpringTest.java#L20
> And also https://github.com/all-of-us/workbench/blob/master/api/src/integration/java/org/pmiops/workbench/IntegrationTestConfig.java#L18

filed https://precisionmedicineinitiative.atlassian.net/browse/RW-6715 through. Going to merge this now...

**Comment by calbach** [comment]
> Actually I think overriding bean is somehow needed in Test. For example, without this, I got BeanOverrideException for the clock bean:
https://github.com/all-of-us/workbench/blob/master/api/src/test/java/org/pmiops/workbench/SpringTest.java#L20
And also https://github.com/all-of-us/workbench/blob/master/api/src/integration/java/org/pmiops/workbench/IntegrationTestConfig.java#L18

That config by itself doesn't override anything though, unless I'm misunderstanding something. You may have gotten a conflict when your local test config also declared it's own clock - that is arguably a bug since the test case really just duplicated work that was done in the base class - the test could have instead just used the protected `clock` field for testing (separately, this is convoluted, so I'm not sure how I feel about the base test pattern in general for test configs).

**Pull request merged**
