### PR TITLE
Mapstruct Demo

### PR DESCRIPTION
**Pull request by ericsong**

### CODE REVIEW

**Comment by jaycarlton** [comment]
Was this form the Hackathon? Do we have a Jira story to fully productize this technique?

**Comment by ericsong** [comment]
Yep. No story, I wanted to demo it at the weekly eng sync before I move forward.

**Comment by jaycarlton** [comment]
Also, FWIW Github added the ability to have a Draft PR a little while back. We can keep those around longer, and filter them out of the list with `is:-draft`.

**Comment by ericsong** [comment]
I'll close it for now.

**Pull request closed without merging**
