### PR TITLE
[no-ticket][risk=no] Remove extraneous modal

### PR DESCRIPTION
**Pull request by petesantos**
Description:

Two different error modals were showing up when there was a deletion error. One linked to the next. Removed the extra modal.
I confirmed with Lou that this was not the intended UX.

I found this while working on the CT workspace changes

### Original UX
original

### Updated UX
corrected

---
**PR checklist**

- [ ] This PR meets the Acceptance Criteria in the JIRA story
- [ ] The JIRA story has been moved to Dev Review
- [X] This PR includes appropriate unit tests
- [X] I have run and tested this change locally
- [ ] I have run the E2E tests on ths change against my local UI and/or API server with `yarn test-local` or [yarn test-local-devup](https://github.com/all-of-us/workbench/blob/master/e2e/README.md#examples)
- [ ] If this includes a UI change, I have taken screen recordings or screenshots of the new behavior and notified the PO and UX designer
- [ ] If this includes an API change, I have updated the appropriate Swagger definitions and notified API consumers
- [ ] If this includes a new feature flag, I have created and linked new JIRA tickets to (a) turn on the feature flag and (b) remove it later

### CODE REVIEW

**Review by dmohs — APPROVED** [review]
Really, really appreciate the animated GIFs for providing super easy-to-digest context.

**Comment by jmthibault79** [comment]
Better UX, thanks.

However I have a few questions I'd like to see answered about the previous code:
1. Is there some reason we want/need to separate workspace deletion errors from generic ones?
2. It seems that there is some "bug report" functionality that this was intended to activate - can we correct that?

**Comment by petesantos** [comment]
@als364 Do you have any insight to @jmthibault79 question: 
> Is there some reason we want/need to separate workspace deletion errors from generic ones?

**Comment by als364** [comment]
No idea. Did I touch these files last or something?

**Comment by petesantos** [comment]
> No idea. Did I touch these files last or something?

Yes - no worries though

**Review by jmthibault79 — APPROVED** [review]
Oops, I missed that the second modal did the error reporting correctly.  No remaining concerns.  Thanks!

**Review by dmohs — COMMENTED** [review]
Net -20! I wonder if I need to start keeping a tally.

**Comment by als364** [comment]
We could probably code a leaderboard if we really wanted to.

**Pull request merged**
