### PR TITLE
[risk=no]Proposal: move mappers to common package org.pmiops.workbench.mappers

### PR DESCRIPTION
**Pull request by jmthibault79**
Description:

I thought it would be nice for all the mappers to be in one place.  LMK if you agree.

---
**PR checklist**

- [ ] This PR meets the Acceptance Criteria in the JIRA story
- [ ] The JIRA story has been moved to Dev Review
- [ ] This PR includes appropriate unit tests
- [ ] I have run and tested this change locally
- [ ] If this includes an API change, I have updated the appropriate Swagger definitions and notified API consumers
- [ ] If this includes a new feature flag, I have created and linked new JIRA tickets to (a) turn on the feature flag and (b) remove it later

### CODE REVIEW

**Comment by ericsong** [comment]
My personal preference would be to organize by feature/domains instead of by function.

Ex. workspace package contains WorkspaceController, Workspace models, WorkspaceDao, WorkspaceMapper

Mainly because I think it scales better long term but I think we can go either way for a small-ish project like workbench. Like most of our other technical decisions, consistency is what mostly matters.

**Comment by gjuggler** [comment]
> My personal preference would be to organize by feature/domains instead of by function.
> 
> Ex. workspace package contains WorkspaceController, Workspace models, WorkspaceDao, WorkspaceMapper
> 
> Mainly because I think it scales better long term but I think we can go either way for a small-ish project like workbench. Like most of our other technical decisions, consistency is what mostly matters.

I agree we should aim to eventually have functionally-separated packages, each containing the full suite of supporting classes.

For the mappers in this PR, it looks like there are reasonably-named functional packages they could go into. And CommonMappers could stay where it is, or go directly into workbench/utils. My vote would be for that.

(Side note: I don't know why it bothers me so, but the workbench/workspaces package should really be named workbench/workspace, preferring the singular form [[I agree with this reasoning](https://softwareengineering.stackexchange.com/questions/75919/should-package-names-be-singular-or-plural)]. And we're almost perfectly inconsistent on this naming rule: cohorts, notebooks, and statusalerts use plural, while conceptset, dataset, and institution use singular.)

**Comment by jaycarlton** [comment]
> : I don't know why it bothers me so, but the workbench/workspaces package should really be named workbench/workspace, preferring the singular form

I got unofficial team approval at one point to make that change and similar ones at some point in the future.

**Comment by jmthibault79** [comment]
Did not realize we were moving to that convention - works for me.

**Pull request closed without merging**
