### PR TITLE
[RW-6355][risk=no] delete unused angular icons

### PR DESCRIPTION
**Pull request by als364**
AFAICT we don't actually use these.

---
**PR checklist**

- [x] This PR meets the Acceptance Criteria in the JIRA story
- [x] The JIRA story has been moved to Dev Review
- [ ] This PR includes appropriate unit tests
- [x] I have run and tested this change locally
- [ ] I have run the E2E tests on ths change against my local UI and/or API server with `yarn test-local` or [yarn test-local-devup](https://github.com/all-of-us/workbench/blob/master/e2e/README.md#examples)
- [ ] If this includes a UI change, I have taken screen recordings or screenshots of the new behavior and notified the PO and UX designer
- [ ] If this includes an API change, I have updated the appropriate Swagger definitions and notified API consumers
- [ ] If this includes a new feature flag, I have created and linked new JIRA tickets to (a) turn on the feature flag and (b) remove it later

### CODE REVIEW

**Review by jmthibault79 — APPROVED** [review]
Tests pass.  Runs locally.  I also can find any references to these.

**Comment by jmthibault79** [comment]
... can't

**Comment by calbach** [comment]
Reminder to copy-paste PR title when merging single-commit PRs (or alternatively, use suitable commit message):  
image

**Comment by als364** [comment]
argh! sorry about that.

**Pull request merged**
