### PR TITLE
[DT-187][risk=no] adding new test CDRs to accurately reflect preprod/prod environments

### PR DESCRIPTION
**Pull request by freemabd**
New test CDR instances:

- all-of-us-ehr-dev.test_R2019q4r3 will now be
RT v4 - all-of-us-ehr-dev.SR2022Q4R6 - sr_2022q4_1
CT v4 - all-of-us-ehr-dev.SC2022Q2R6 - sc_2022q4_1

- all-of-us-ehr-dev.test_R2019q4r3_backup will now be
RT v3 - all-of-us-ehr-dev.SR2022Q2R6 - synth_r_2019q4_44(did not rebuild since CDR indices aren't backwards comp)
CT v3 - all-of-us-ehr-dev.SC2022Q2R6 - synth_c_2019q4_40(did not rebuild since CDR indices aren't backwards comp)
RT v2 - all-of-us-ehr-dev.SR2022Q2R6 - synth_c_2019q4_40(did not rebuild since CDR indices aren't backwards comp)

Moving forward, when creating a CDR index please use the following naming convention in test
RT - sr_2022q4_x
CT - sc_2022q4_x

Updated the CDR playbook to reflect changes: https://docs.google.com/document/d/1St6pG_EUFB9oRQUQaOSO7a9UPxPkQ5n4qAVyKF9j9tk/edit#

### CODE REVIEW

**Comment by chenchals** [comment]
> New test CDR instances:
> 
> * all-of-us-ehr-dev.test_R2019q4r3 will now be
>   RT v4 - all-of-us-ehr-dev.SR2022Q4R6 - sr_2022q4_1
>   CT v4 - all-of-us-ehr-dev.SC2022Q2R6 - sc_2022q4_1
> * all-of-us-ehr-dev.test_R2019q4r3_backup will now be
>   RT v3 - all-of-us-ehr-dev.SR2022Q2R6 - synth_r_2019q4_44(did not rebuild since CDR indices aren't backwards comp)
>   CT v3 - all-of-us-ehr-dev.SC2022Q2R6 - synth_c_2019q4_40(did not rebuild since CDR indices aren't backwards comp)
>   RT v2 - all-of-us-ehr-dev.SR2022Q2R6
> 
> Moving forward, when creating a CDR index please use the following naming convention in test RT - sr_2022q4_x CT - sc_2022q4_x

This sr_ and sc_ naming is for test/dev environment only, right? and not for preprod/prod.

**Review by chenchals — APPROVED** [review]
Would these also change for staging/stable/perf eventually?

**Comment by freemabd** [comment]
> Would these also change for staging/stable/perf eventually?

Pushed changes for these as well.

**Comment by freemabd** [comment]
> > New test CDR instances:
> > 
> > * all-of-us-ehr-dev.test_R2019q4r3 will now be
> >   RT v4 - all-of-us-ehr-dev.SR2022Q4R6 - sr_2022q4_1
> >   CT v4 - all-of-us-ehr-dev.SC2022Q2R6 - sc_2022q4_1
> > * all-of-us-ehr-dev.test_R2019q4r3_backup will now be
> >   RT v3 - all-of-us-ehr-dev.SR2022Q2R6 - synth_r_2019q4_44(did not rebuild since CDR indices aren't backwards comp)
> >   CT v3 - all-of-us-ehr-dev.SC2022Q2R6 - synth_c_2019q4_40(did not rebuild since CDR indices aren't backwards comp)
> >   RT v2 - all-of-us-ehr-dev.SR2022Q2R6
> > 
> > Moving forward, when creating a CDR index please use the following naming convention in test RT - sr_2022q4_x CT - sc_2022q4_x
> 
> This sr_ and sc_ naming is for test/dev environment only, right? and not for preprod/prod.

The answer is stated in the description

**Pull request merged**
