### PR TITLE
[RW-712][risk=no] Enforce registered in staging

### PR DESCRIPTION
**Pull request by calbach**
This will have implications for the release QA process. This will also force us to start thinking about some new UX issues in the first-sign-in flow. Timing is not urgent if we think this will cause significant short-term pain before some of the account creation flow changes are in.

### CODE REVIEW

**Comment by blrubenstein** [comment]
I'm actually most worried about shared accounts with this. Because I believe ID verification is a gating factor on registered access, and it would be nice to have a shared account that has the ID verification review authority. 

Other than that, I think contact email verification is the other thing that needs to go in, because we don't currently have a way to do that with our mailchimp deprecation. We should probably remove that need until we have a process in place for that.

**Comment by calbach** [comment]
AFAIK I don't have any access to any "shared accounts". I've already put instructions in the playbook for doing manual ID verification, though it will be a bit of a pain initially.

Won't mailchimp keep working until we switch to the new thing? That said, I'm fine to wait on that.

**Comment by calbach** [comment]
Ah, I just realized we have the temporary password via email thing setup now, and I think @rushtong mentioned work on the email verification status - so I think I'll wait on that before continuing with this PR.

**Comment by calbach** [comment]
Alright, lets try this out. Since I'm scheduled to do the next release, I will be the one to suffer the initial QA impact.

**Pull request merged**
