### PR TITLE
Attempt to update institutions but seeing NPE

### PR DESCRIPTION
**Pull request by jmthibault79**
Description:

I updated `LoadInstitutions` as shown here and attempted to load a JSON file of institutions to update a few of them in the DB, formatted like this:
```
[{
        "shortName": "NIH",
        "displayName": "National Institutes of Health",
        "organizationTypeEnum": "ACADEMIC_RESEARCH_INSTITUTION",
        "emailDomains": [
            "nih.gov"
        ],
        "emailAddresses": []
    },
...
]
```

However I saw NPE with a stacktrace:
https://gist.github.com/jmthibault79/3d1d4957565eca904a473c8e6c5faac2

My other changes in this PR are attempts to fix this, which do not work.

Where could this null be sneaking in?

---
**PR checklist**

- [ ] This PR meets the Acceptance Criteria in the JIRA story
- [ ] The JIRA story has been moved to Dev Review
- [ ] This PR includes appropriate unit tests
- [ ] I have run and tested this change locally
- [ ] If this includes an API change, I have updated the appropriate Swagger definitions and notified API consumers
- [ ] If this includes a new feature flag, I have created and linked new JIRA tickets to (a) turn on the feature flag and (b) remove it later

### CODE REVIEW

**Comment by jmthibault79** [comment]
Each JSON entry in my file has an empty array for `emailAddresses`, and the existing DB entries should also have no rows in the address table.

**Comment by jaycarlton** [comment]
Psychic debugging: are any generated classes setting missing lists to null instead of empty? Swagger doesn't let you specify an initial value for a list.

**Comment by jmthibault79** [comment]
Returning to this because it would be very useful for https://precisionmedicineinitiative.atlassian.net/browse/RW-4952

Still no luck.

**Comment by jmthibault79** [comment]
A more recent stack trace: https://gist.github.com/jmthibault79/cbb82442523f69eeb4481cad4b1c7b8f

**Comment by jmthibault79** [comment]
Resolved by a `@Transactional` hack in https://github.com/all-of-us/workbench/pull/3585

A proper solution is https://precisionmedicineinitiative.atlassian.net/browse/RW-4968

**Pull request closed without merging**
