### PR TITLE
[risk=no][RW-8531] Update CDR config to use the new manifest instead of the single sample path

### PR DESCRIPTION
**Pull request by tarekmamdouh**
Description:

---
**PR checklist**

- [x] This PR meets the Acceptance Criteria in the JIRA story
- [x] The JIRA story has been moved to Dev Review
- [ ] This PR includes appropriate unit tests
- [ ] I have added explanatory comments where the logic is not obvious
- [ ] I have run and tested this change locally, and my testing process is described here
- [ ] If this includes a new feature flag, I have created and linked new JIRA tickets to (a) turn on the feature flag and (b) remove it later
- [ ] If this includes an API change, I have run the E2E tests on this change against my local server with [yarn test-local](https://github.com/all-of-us/workbench/blob/master/e2e/README.md#examples) because this PR won't be covered by the CircleCI tests 
- [ ] If this includes a UI change, I have taken screen recordings or screenshots of the new behavior and notified the PO and UX designer in [Slack](https://pmi-engteam.slack.com/archives/C02MWP2RN5P)
- [ ] If this change impacts deployment safety (e.g. removing/altering APIs which are in use) I have documented these in the description
- [ ] If this includes an API change, I have updated the appropriate Swagger definitions and updated the appropriate API consumers
  * AoU UI
  * [Perf tests](https://github.com/broadinstitute/mcnulty/blob/develop/src/test/scala/services/AoU.scala)
  * [Researcher Directory export](https://github.com/all-of-us/workbench/wiki/Researcher-Directory-(RDR-export))
  * Cron tasks - for Offline*Controllers
  * SumoLogic - for EgressAlert

### CODE REVIEW

**Review by yonghaoy — COMMENTED** [review]
Would that break our existing microarrayVcfSingleSampleStoragePath usage? https://cs.github.com/?scope=org%3Aall-of-us&scopeName=all-of-us&q=microarrayVcfSingleSampleStoragePath?

**Comment by yonghaoy** [comment]
> Would that break our existing microarrayVcfSingleSampleStoragePath usage? https://cs.github.com/?scope=org%3Aall-of-us&scopeName=all-of-us&q=microarrayVcfSingleSampleStoragePath?

Or cleanup all those usage?

**Comment by tarekmamdouh** [comment]
@yonghaoy No it shouldn't break anything. I'll create another ticket to cleanup this field. It's already mentioned in the story description.

**Review by yonghaoy — APPROVED** [review]

**Comment by tarekmamdouh** [comment]
@yonghaoy As discussed, I brought back microarrayVcfSingleSampleStoragePath with an empty value and created a new story for the cleanup [RW-8846](https://precisionmedicineinitiative.atlassian.net/browse/RW-8846)

**Pull request merged**
