### PR TITLE
[risk=no] Ignore any java/kotlin/Ruby changes for puppeteer runs

### PR DESCRIPTION
**Pull request by calbach**

### CODE REVIEW

**Review by aweng98 — APPROVED** [review]
Make sense. We can change back when local API server working in CI.

**Comment by aweng98** [comment]
I realize we could remove `api` directory from this check.
https://github.com/all-of-us/workbench/blob/d9c3453ef5d1bad6c4361f5415a100c4804bad86/.circleci/config.yml#L305

**Comment by calbach** [comment]
@aweng98 technically the api dir would still cover changes to Swagger files, which would affect the Puppeteer test code - but it's very unlikely Puppeteer would catch an issue here (that wouldn't be caught at compilation).

Also - do we still need this extra check since we have the ignores file?

**Comment by aweng98** [comment]
I think we do. Listed file extensions in ignore file is not all-inclusive. like `.rb`, `json`, `.properties`, etc.

**Pull request merged**
