### PR TITLE
RW-10951 higher memory for dataproc cluster master node

### PR DESCRIPTION
**Pull request by Qi77Qi**
---
**PR checklist**

- [ ] I have included an issue ID or "no ticket" in the PR title as outlined in [CONTRIBUTING.md](https://github.com/all-of-us/workbench/blob/main/.github/CONTRIBUTING.md).
- [ ] I have included a risk tag of the form `[risk=no|low|moderate|severe]` in the PR title as outlined in [CONTRIBUTING.md](https://github.com/all-of-us/workbench/blob/main/.github/CONTRIBUTING.md).
- [ ] I have manually tested this change and my testing process is described above.
- [ ] This change includes appropriate automated tests, and I have documented any behavior that cannot be tested with code.
- [ ] I have added explanatory comments where the logic is not obvious.
- One or more of the following is true:
  - [ ] This change is intended to complete a JIRA story, so I have checked that all AC are met for that story.
  - [ ] This change fixes a bug, so I have ensured the steps to reproduce are in the Jira ticket or provided above.
  - [ ] This change impacts deployment safety (e.g. removing/altering APIs which are in use), so I have documented the impacts in the description.
  - [ ] This change includes a new feature flag, so I have created and linked new JIRA tickets to (a) turn on the feature flag and (b) remove it later.
  - [ ] This change modifies the UI, so I have taken screenshots or recordings of the new behavior and notified the PO and UX designer in [Slack](https://pmi-engteam.slack.com/archives/C02MWP2RN5P).
  - [ ] This change modifies API behavior, so I have run the relevant E2E tests locally because API changes are not covered by our PR checks.
  - [ ] None of the above apply to this change.

### CODE REVIEW

**Review by jmthibault79 — DISMISSED** [review]

**Review by yonghaoy — COMMENTED** [review]
The issue we are having is memlimit/spark driver memory number is not set correctly. I think the correct fix should be figure out the right algorithm.
For this change, we should still allow user to create dataproc or get confirmed from data scientist team that smaller machine should not be supported.
Dataproc still supports n1-standard-4, so we should still support it. This machine is cheaper and is still good enough some type of analysis.

**Comment by yonghaoy** [comment]
> The issue we are having is memlimit/spark driver memory number is not set correctly. I think the correct fix should be figure out the right algorithm. For this change, we should still allow user to create dataproc or get confirmed from data scientist team that smaller machine should not be supported. Dataproc still supports n1-standard-4, so we should still support it. This machine is cheaper and is still good enough some type of analysis.

Few things we can do:
1: Confirm with Moira, Chris, Data Scientist that we are okay of stop supporting n1-standard-4 machines. 
2: Maybe refered this back once we solved Hail issue. 
Also, I think the OOM issue does not 100% happened to all `n1-stanard-4` machines, it is related with the analysis & file. when I use the same code running another VDS file that Hail eng shared with me, there is no error.

**Comment by Qi77Qi** [comment]
It's definitely true that this is analysis specific. But I think it doesn't hurt to increase default master node memory a bit so that users have less memory issues. Master node is usually pretty memory-intensive.

Regarding the memory algorithm, I don't know if we can come up with an accurate "algorithm", it's more of a best effort.

**Comment by jmthibault79** [comment]
@Qi77Qi changing this value does not just affect the default - it makes it impossible to go lower than this in the UI.

**Comment by Qi77Qi** [comment]
@jmthibault79 yea, that what I'm figured...just thought it's good to increase

anyways, I think we can roll out the image upgrade for now and if many users run into memory issue, we can then update

**Pull request closed without merging**
