### PR TITLE
[RW-916][risk=no] Upgrade to Guava 25.1 to fix local dev

### PR DESCRIPTION
**Pull request by calbach**
This appears to fix the issue for me locally.

### CODE REVIEW

**Comment by rushtong** [comment]
One thing I don't see in any of our gradle tasks is a call with `--refresh-dependencies`. I'm not sure where the best place is to do that, perhaps the `clean` task, but that might also help.

**Comment by calbach** [comment]
@freemabd1 did you do a docker-clean as well?

**Comment by freemabd1** [comment]
@calbach I didn't do a docker-clean... but I will try that now to confirm that it's still an issue.

**Comment by calbach** [comment]
@rushtong I do not claim to have identified the root cause. I think there's a bad interaction between dependencies somewhere, and at least on my machine this change jiggled them back around to working. I observed that downgrading to 23.0 or lower seemed to fix this as well, so I just tried 25.1 on a whim and it worked for me. We'll see if it does anything for Brian though..

**Comment by freemabd1** [comment]
@rushtong @calbach I have confirmed that downgrading has worked for me.

**Comment by freemabd1** [comment]
@calbach after doing a docker-clean, I'm still seeing the same error

**Comment by calbach** [comment]
I guess I should merge this PR? This fixes things for me, doesn't make things obviously *worse* for @freemabd1 , and also addresses the security issue.

**Pull request merged**
