### PR TITLE
[risk=low][no ticket][Snyk] Upgrade 5 UI packages

### PR DESCRIPTION
**Pull request by SrushtiGangireddy**
<p>This PR was automatically created by Snyk using the credentials of a real user.</p><br /><h3>Snyk has created this PR to upgrade @types/react-modal from 3.13.1 to 3.16.1.</h3>

:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.
<hr/>

- The recommended version is **2 versions** ahead of your current version.
- The recommended version was released **a month ago**, on 2023-09-27.

<hr/>

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs.*

For more information:  

🧐 [View latest project report](https://app.snyk.io/org/srushtigangireddy/project/fc523b3f-d450-4f71-972a-b0e6194899ac?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/srushtigangireddy/project/fc523b3f-d450-4f71-972a-b0e6194899ac/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr)

🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/srushtigangireddy/project/fc523b3f-d450-4f71-972a-b0e6194899ac/settings/integration?pkg&#x3D;@types/react-modal&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;referral&amp;page&#x3D;upgrade-pr#auto-dep-upgrades)

### CODE REVIEW

**Comment by jmthibault79** [comment]
Tested locally.

react-modal: Observed that a modal worked correctly
react-onclickoutside: Observed that clicking outside of a PopupTrigger caused it to close
types-color: Observed that our use of `Color` compiled without issue
primereact: Observed various primereact components which all worked as normal

**Comment by jmthibault79** [comment]
e2ev2 error looks like it may be related to #8123 ?
```
TimeoutError: Waiting for selector `[aria-label="Institution"]` failed: Waiting failed: 2000ms exceeded

      32 |
      33 |   await page.waitForSelector('#account-creation-institution') // Institution Page
    > 34 |   await page.waitForSelector('[aria-label="Institution"]')
```

**Comment by jmthibault79** [comment]
Merging.  @NehaBroad is looking at the unrelated e2ev2 error.

**Review by NehaBroad — APPROVED** [review]
I did confirm: modal/primereact table are working fine. 
I was not able to test google captcha

**Pull request merged**
