### PR TITLE
rw 245 pyclient

### PR DESCRIPTION
**Pull request by johnstill**
If we're going to use PyPi, all we need are credentials and we're ready to go.  If not, I still think we should be hosting and installing from proper archives rather than a special and specially maintained git branch.

Opened for review and discussion; requires a decision on PyPi before merge.

If there are any questions about what files are included and why, please feel free to ask.

EDIT: there are a few other details to wrap up - metadata such as maintainer / maintainer email, and I'll need to update the README to reflect the changes in this PR.

### CODE REVIEW

**Comment by johnstill** [comment]
@danqrodney that's my question for you guys.  If PyPi is approved, the archive just lives there.  Otherwise I might suggest a dedicated repo, possibly as a submodule, so we can continue to host / track client versions without dirtying the main repo.  That kind of data repo goes against github's TOS though.

**Comment by danqrodney** [comment]
Based on comments by David Bernick on #security, I think we should be OK to use this and publish to PyPi. We'll need to have a step in our build where we use "safety check" (or something like it) to scan for security vulnerabilities in any dependencies of our Python library. Beyond that it should be fine.

**Comment by johnstill** [comment]
Ok. Soon as someone sends me PyPi credentials I'll wrap this up (update the docs, re-review everything, merge).

**Comment by johnstill** [comment]
Closing because the PR is fairly old and this issue is on indefinite hiatus.

**Pull request closed without merging**
