### PR TITLE
Remove SSL warnings for DB connection

### PR DESCRIPTION
**Pull request by dmohs**

### CODE REVIEW

**Comment by markfickett** [comment]
Could you drop a comment in there saying why skipping SSL is OK / desirable? I assume it's something like internal Google network + no certificate for the SQL instance, but skipping SSL is such a departure from the norm it'd be good to keep rationale.

**Comment by dmohs** [comment]
This change only affects local development where the connection is across the internal docker network. The Cloud SQL Proxy "automatically encrypts traffic to and from the database," [1] but I'm not changing that here.

[1] https://cloud.google.com/sql/docs/mysql/sql-proxy

Is this obvious-enough given the hostname of "db" (which pretty much has to be local) or is a comment still worthwhile?

**Comment by markfickett** [comment]
Maybe just a file-level comment saying "details for connecting to MySQL in docker-compose" (since the file's path doesn't imply it's specific to the dev environment)?

**Comment by dmohs** [comment]
I like that. Done.

**Pull request merged**
