### PR TITLE
[RW-3316][risk=no] Clear notebook load timer on navigate

### PR DESCRIPTION
**Pull request by calbach**

### CODE REVIEW

**Comment by jmthibault79** [comment]
I'm not seeing where `runClusterTimer` is triggered - is that elsewhere?

**Comment by calbach** [comment]
The timer just tracks a pending timeout, which gets invoked via `retry()`, which gets called here: https://github.com/all-of-us/workbench/pull/2760/files#diff-2ea8624017c9c5dbbed2d67d1d2e6c83L150-L154

**Comment by calbach** [comment]
i.e. `runClusterTimer` is not a function, but an ID for a `setTimeout` so that we can clear it later.

**Comment by jmthibault79** [comment]
got it, thx

**Pull request merged**
