### PR TITLE
[RW-6154][risk=no]  Remove load data dictionary from deploy and delete code (Data Dictionary)

### PR DESCRIPTION
**Pull request by NehaBroad**
Data dictionary data has been moved to CDR as part of CDR build, so we no longer need this code that loads the data from YAML file during deploy

---
**PR checklist**

- [x] This PR meets the Acceptance Criteria in the JIRA story
- [x] The JIRA story has been moved to Dev Review
- [ ] This PR includes appropriate unit tests
- [x] I have run and tested this change locally
- [ ] I have run the E2E tests on ths change against my local UI and/or API server with `yarn test-local` or [yarn test-local-devup](https://github.com/all-of-us/workbench/blob/master/e2e/README.md#examples)
- [ ] If this includes a UI change, I have taken screen recordings or screenshots of the new behavior and notified the PO and UX designer
- [ ] If this includes an API change, I have updated the appropriate Swagger definitions and notified API consumers
- [ ] If this includes a new feature flag, I have created and linked new JIRA tickets to (a) turn on the feature flag and (b) remove it later

### CODE REVIEW

**Review by freemabd — COMMENTED** [review]
Should we also remove the following:

1. https://github.com/all-of-us/workbench/blob/6e1c95893fd023760f1628220674d3094c466fcc/api/build.gradle#L772-L772
2. https://github.com/all-of-us/workbench/blob/6e1c95893fd023760f1628220674d3094c466fcc/api/tools/README.md#L3-L3

**Review by freemabd — COMMENTED** [review]
I was able to dev-up locally and everything works as expected.

**Comment by NehaBroad** [comment]
Oh thank you i missed these files

**Review by ericsong — APPROVED** [review]

**Comment by ericsong** [comment]
is the table going to be dropped in a follow up PR?

**Comment by NehaBroad** [comment]
Yes, waiting for this PR to merge

**Pull request merged**
