### PR TITLE
[RW-3602][risk=low]Migrate from org.junit.Assert to google truth

### PR DESCRIPTION
**Pull request by yonghaoy**
Description:

---
**PR checklist**

- [ ] This PR meets the Acceptance Criteria in the JIRA story
- [ ] The JIRA story has been moved to Dev Review
- [ ] This PR includes appropriate unit tests
- [ ] I have run and tested this change locally
- [ ] I have run the E2E tests on ths change against my local UI + API server with `yarn test-local`
- [ ] If this includes a UI change, I have taken screen recordings or screenshots of the new behavior and notified the PO and UX designer
- [ ] If this includes an API change, I have updated the appropriate Swagger definitions and notified API consumers
- [ ] If this includes a new feature flag, I have created and linked new JIRA tickets to (a) turn on the feature flag and (b) remove it later

### CODE REVIEW

**Review by calbach — APPROVED** [review]
Nice, thanks for this cleanup.

Per your standup question around whether there was a better way to do the refactoring: I suspect there was a way to do this somewhat easily using Intellij, but I'm not an expert with it. Personally I would probably have gotten ~80% done with `sed` + `./gradlew spotlessApply` (formatting), then fixed the rest by hand.

**Comment by yonghaoy** [comment]
> Nice, thanks for this cleanup.
> 
> Per your standup question around whether there was a better way to do the refactoring: I suspect there was a way to do this somewhat easily using Intellij, but I'm not an expert with it. Personally I would probably have gotten ~80% done with `sed` + `./gradlew spotlessApply` (formatting), then fixed the rest by hand.

sed or regex replace way is not enough because the order of expected and actual. The order should be:
```
assertEqual(expected, actual);
assertThat(actual).isEqualTo(expected);
```

I don't think current assertEqual follows that.

**Comment by jmthibault79** [comment]
This is the IntelliJ feature you're thinking of: https://www.jetbrains.com/help/idea/structural-search-and-replace.html

I am also not very experienced with how it works.

**Comment by yonghaoy** [comment]
> This is the IntelliJ feature you're thinking of: https://www.jetbrains.com/help/idea/structural-search-and-replace.html
> 
> I am also not very experienced with how it works.

Thanks! But for the same reason I mentioned above, we need 
```
assertEqual(expected, actual);
assertThat(actual).isEqualTo(expected);
```

But our current code has mixed of 
```
assertEqual(expected, actual);
assertEqual(actual, expected);
```

So I manually went those code through.

**Pull request merged**
