### PR TITLE
Revert "[RW-5662][risk=no] Puppeteer Fix flaky Cohort UI test"

### PR DESCRIPTION
**Pull request by aweng98**
Reverts all-of-us/workbench#4080

### CODE REVIEW

**Comment by aweng98** [comment]
😔  Saw CH comments in PR after merge happened. Reverting commit.

**Comment by calbach** [comment]
I think the current state is OK temporarily. I would suggest either myself or @dolbeew take on refactoring the help sidebar as suggested in my previous comment - i.e. don't render sidebar tabs if they aren't being actively displayed. We can combine that change with this revert, and flakiness should be eliminated.

**Comment by calbach** [comment]
Sent https://github.com/all-of-us/workbench/pull/4084

**Comment by aweng98** [comment]
#4084 is merged. I'll be able to merge if someone is able to approve.

**Review by calbach — APPROVED** [review]
Sure - please rebase or merge master and verify it still passes

**Comment by aweng98** [comment]
Okay. In that case, I'll have to wait because there are no more billing projects at this time. Thanks.

**Comment by aweng98** [comment]
Ran test suites few times on localhost. There was no failure related to hidden menu.

**Pull request merged**
