### PR TITLE
[RW-676] Removed colon after NIH name. Made research purpose field into fixed … Security Impact: None.

### PR DESCRIPTION
**Pull request by katevoss**
…width, and added minimum width to cards on new Workspace

See https://precisionmedicineinitiative.atlassian.net/browse/RW-676

### CODE REVIEW

**Comment by rushtong** [comment]
Thank you @katevoss! I will get to this as soon as possible.

**Comment by rushtong** [comment]
I can still see the original bug. Tagging @blrubenstein to see if you want to try another solution to this problem.

screen shot 2018-06-04 at 8 37 55 am

**Comment by blrubenstein** [comment]
I realized this had the wrong ticket tagged on it. @rushtong ptal

**Comment by rushtong** [comment]
Executively deciding to move this through and will update the ticket.

**Pull request merged**
