### PR TITLE
[RW-6041][risk=no] Stop width from changing as help sidebar opens

### PR DESCRIPTION
**Pull request by als364**
https://user-images.githubusercontent.com/1847690/107283895-00884280-6a2b-11eb-8e48-c2637cb917a5.mov

---
**PR checklist**

- [x] This PR meets the Acceptance Criteria in the JIRA story
- [x] The JIRA story has been moved to Dev Review
- [ ] This PR includes appropriate unit tests
- [x] I have run and tested this change locally
- [ ] I have run the E2E tests on ths change against my local UI and/or API server with `yarn test-local` or [yarn test-local-devup](https://github.com/all-of-us/workbench/blob/master/e2e/README.md#examples)
- [x] If this includes a UI change, I have taken screen recordings or screenshots of the new behavior and notified the PO and UX designer
- [ ] If this includes an API change, I have updated the appropriate Swagger definitions and notified API consumers
- [ ] If this includes a new feature flag, I have created and linked new JIRA tickets to (a) turn on the feature flag and (b) remove it later

### CODE REVIEW

**Review by calbach — APPROVED** [review]
I'm not sure if it's just lag in the recording, but while the help panel slides in smoothly, it seems like the runtime panel spawns into existence halfway across the page. Is there an ordering issue around when the panel content is being set, and when the animation style is getting set?

**Comment by als364** [comment]
No, you're right, something's going on there. Will look into it

**Comment by als364** [comment]
I'm having trouble tracking down exactly where the issue is with the jumping animation. Not sure how much effort I should put into fixing this, or whether it's preferable to have the original bug vs the jumping.

**Comment by als364** [comment]
(Fixing the original bug by messing with flex-basis, grid min-width, text-overflow etc. in the runtime panel and the help panel would likely be more effort than it's worth)

**Comment by calbach** [comment]
I leave it your judgement which is better (or you can check with Shimon) - so you can drop or merge accordingly. I agree it is not worth pursuing further if you've not been able to resolve it within a cumulative ~day.

**Comment by als364** [comment]
yeah, have a message out to Shimon currently. IMO the slight jump is less annoying than the constant word/element rewrap.

**Pull request merged**
