### PR TITLE
Checkpoint

### PR DESCRIPTION
**Pull request by dmohs**

### CODE REVIEW

**Comment by dmohs** [comment]
@markfickett Signing in and out once works fine. Signing in again does nothing. Thoughts?

**Comment by dmohs** [comment]
@markfickett Also, process note: It was painful to have to lint before I pushed this checkpoint branch.

**Comment by jmandel** [comment]
@dmohs I think you may have forgotten to check in the component at `app/views/sign-in`? (The old `login` view is present, but not the new `sign-in` one.)

**Comment by jmandel** [comment]
+1 on the process note: another issue with linting-before-push is that the linter checks the *current state of files* rather than the contents that are about to be pushed. This means I can do `git add my-new-stuff`, then `git commit` then `git push`, and when the linter complains, I make fixes... and then `git push` successfully. Unfortunately, the end state is that I've pushed my unlined code and have a bunch of local lint fixes that are unstaged.

**Comment by markfickett** [comment]
This is subsumed by a new PR I'm working on with Josh -- it was easier to get login + Swagger + bearer token working all together than separate PRs, so I'll go ahead and close this PR.

**Pull request closed without merging**
