### PR TITLE
[no ticket][risk=no] Puppeteer Update file names pattern for skipping tests in CircleCI

### PR DESCRIPTION
**Pull request by aweng98**
Update ignore file name patterns. It will reduces numbers of test runs in CircleCI.

### CODE REVIEW

**Comment by aweng98** [comment]
@calbach I had an idea on how to reduce unnecessary Puppeteer testing in CircleCI.  If current commit which triggered CI workflow contains files that match skip patterns, then Puppeteer test job will skip running. Combined files changed in PR will not used to determine skip.

**Review by calbach — COMMENTED** [review]
I don't follow. This should be identical to the current behavior by my understanding, except that it harcodes the assumption that we're using "squash and commit" in our GitHub repo. Can you explain the rationale for this change?

**Comment by calbach** [comment]
Oh wait - is your goal here around presubmit runs on PRs? Rather than on post-master merge?

**Comment by calbach** [comment]
If so, the problem with this approach is that 1 push !== 1 commit. It's typical that someone might push up multiple commits simultaneously. We don't want to skip in this situation.

**Comment by calbach** [comment]
Another idea to reduce e2e runs would be to ignore server code changes, e.g. `.java`. Puppeteer currently does not exercise any API code paths.

**Comment by aweng98** [comment]
Yes, my intention is to reduce runs on PR commits. This is an [example of commit](https://app.circleci.com/pipelines/github/all-of-us/workbench/6525/workflows/6cb0d67b-761c-4343-a0a4-b9c39b3604ae) that e2e tests should not have run. 
A potential problem as you have mentioned is 1 push !== 1 commit. I thought that won't happen often. Tests run when merge into master branch would catch any issue if was not caught by PR run.
Are you suggesting to ignore all `*.java` files in `api` dir? That's a lot of files to ignore. Current ignore patterns are listed in [e2e-job-ignore-patterns.txt](https://github.com/all-of-us/workbench/blob/master/.circleci/e2e-job-ignore-patterns.txt)

**Comment by calbach** [comment]
Yes, that's what I'm suggesting, i.e. add `.java` to that file. Why does the number of files matter? As of today, given that Puppeteer only talks to the test API server (not a local server), Puppeteer does not exercise any of our Java / API code, so there's no point in running Puppeteer on a PR for API code.

Both scenarios seem about equally likely to me: pushing a single UI-less commit on a UI PR vs pushing multiple commits at once. There's also force pushing after a rebase, which this approach would also have issues with. My concern is that it's difficult logic to explain, and the side effect is that Puppeteer will appear to pass, when in reality it was skipped.

**Comment by aweng98** [comment]
Got it. Made the change. It's a small change but I think it's having a big impact because we could avoid (some) unnecessary e2e testing in CircleCI.

**Review by calbach — APPROVED** [review]

**Pull request merged**
