### PR TITLE
Update to webpack-dev-server 3.1.11 to fix vulnerability

### PR DESCRIPTION
**Pull request by jmthibault79**
See vulnerability here: https://github.com/all-of-us/workbench/network/alert/ui/yarn.lock/webpack-dev-server/open

### CODE REVIEW

**Comment by calbach** [comment]
Appears to still be resolving to webpack 3.8, per snyk error

**Comment by jmthibault79** [comment]
@calbach Wouldn't 3.8.0 be an acceptable upgrade from 3.1.11 ?  Also, I don't seem to have the correct access to view Snyk.

**Comment by calbach** [comment]
Invited you to Snyk. I think this is resolving an issue found by GitHub, and introducing an issue found by Snyk. I don't know how to assess this tradeoff. Snyk does not offer a clear workaround.

Snyk is part of our official static dependency analysis. But all else aside, pulling a more recent version of a package is probably a good thing. Perhaps when you can look at the Snyk report you can thread the needle with an older (but still >3.1.11) version.

**Comment by jmthibault79** [comment]
3.1.11 is the good version - trying to resolve this by specifying it exactly.  Apparently my earlier attempt to upgrade was too loose, and it decided 3.8.0 (the latest) was close enough.

**Pull request merged**
