### PR TITLE
[RW-5329][risk=low] Attempt to upgrade the notebook image again

### PR DESCRIPTION
**Pull request by calbach**
- Update to newer TensorFlow python package.
- Update numpy to match documented version (this fixes pandas_profiling in our tests).
- Reinstall AoU fork of bigrquery (new patch taken from ahead of the main package)

Manual testing:
- Ran a local bash shell with the new docker image
- Opened python3 and executed Alex's new test content (derived from manual QA notebook): https://github.com/all-of-us/workbench/blob/0d68c9bfd3420206f0df277b85b757a0175a8385/e2e/resources/python-code/import-libs.py 
- Opened R and executed Alex's new test content: https://github.com/all-of-us/workbench/blob/0d68c9bfd3420206f0df277b85b757a0175a8385/e2e/resources/r-code/import-libs.R

### CODE REVIEW

**Comment by jmthibault79** [comment]
NotebooksIntegrationTest is failing

**Comment by jmthibault79** [comment]
Correct versions confirmed for numpy and tensorflow: Screen Shot 2020-08-18 at 5 51 42 PM

**Comment by calbach** [comment]
That test apparently just looks at whether Leo in dev is currently returning an OK status. This is not super useful to run on a PR, though I guess it would at least test any kind of API request machinery. None of that stuff has changed in the PR so I would assume unrelated. I will rerun to make it green.

**Comment by calbach** [comment]
Thanks for the additional manual testing, much appreciated.

**Pull request merged**
