### PR TITLE
[no ticket][risk=no] Enable Puppeteer testing in staging env

### PR DESCRIPTION
**Pull request by aweng98**
Issue: Puppeteer tests fail randomly in staging with the default appengine settings in staging:
- Default is `min_idle_instances = 0, max_instances = 10, instance_class = 'F1'` [devstart.rb#L70](https://github.com/all-of-us/workbench/blob/25b429cfb3b1cad7d2363dee64bce03d3bfe9f8c/api/libproject/devstart.rb#L70)

Google Cloud Console error is `Request was aborted after waiting too long to attempt to service your request.`

Experimented with some different appengine settings, following two works (no Puppeteer tests failures):
- `(4, 10, 'F1')`
- `(0, 10, 'F2')`

Increasing number of idle instances or increasing class type to `F2` both works. 

Difference in cost per hour per usage between `F1` and `F2` class is $0.05. Idle `F1` instance costs per hour is $0.05. Having a higher number of idle instances cost $ every hour (used or not). A higher class type (F2) costs 5 cents per hour only when used. I think changing to F2 makes sense because it's cost-effective.

### CODE REVIEW

**Review by calbach — APPROVED** [review]
Interesting, thanks for testing out the different configurations. Do you mind also capturing in the description the other descriptions you tried (but failed?), would be useful to know this for later.

I'm honestly a bit surprised that increasing the class helped - this might indicate that resource class helps to improve our server initialization speed. For future reference, in the cases where you saw `Request was aborted after waiting too long to attempt to service your request`, did the same request logs contain server initialization? i.e. a bunch of Spring Boot initialization, and also were these failures always on the initial requests to the server task?

**Comment by calbach** [comment]
Also agreed: increasing the resource class is preferred over having minIdle if they both work.

**Comment by aweng98** [comment]
Changes that did not help are:
- set <min-pending-latency> to add instances faster
- set <max-pending-latency> to add instances faster
- set idle instances = 3

Other changes that helped:
- (0, 10, 'F4')
- (5, 10, 'F1')

Summary: num of idle-instances >= 4 helped without need for a bigger class type. And, any class type bigger than F1 also helped.
Yes, I'll keep an eye on failure if happen again for server initialization logs.

**Comment by calbach** [comment]
Just noticed: can you switch the PR title? Seems to be incorrect since this doesn't actually make any changes to the staging CI workflow.

**Pull request merged**
