### PR TITLE
[risk=no][RW-9315] Update application's root font-size

### PR DESCRIPTION
**Pull request by evrii**
Description: 
Updated the root font size (font-size of html tag) from 24px(size from Clarity) to 16px (default browser size)~~100% (this represents 100% of the browser's font-size which defaults to 16px)~~. As a result, every instance of rem in the application had to be updated. The rem values were all multiplied by 1.5 (24px[old size]/16px[new size] = 1.5).

Update:
Our styling breaks down when using a variable font-size. Good find @Peter-Lavigne. Before this PR, we had a fixed font size, so we were ignoring user browser font size. With that said, I changed this PR to also have a fixed font-size but the standard rather then the older value. I think that it will be important to make our app support variable font sizing, but I think that is outside of the scope of this ticket. I think that this will be part of a larger discussion of making our app responsive.

---
**PR checklist**

- [ ] This PR meets the Acceptance Criteria in the JIRA story
- [ ] The JIRA story has been moved to Dev Review
- [ ] This PR includes appropriate unit tests
- [ ] I have added explanatory comments where the logic is not obvious
- [ ] I have run and tested this change locally, and my testing process is described here
- [ ] If this includes a new feature flag, I have created and linked new JIRA tickets to (a) turn on the feature flag and (b) remove it later
- [ ] If this includes an API change, I have run the E2E tests on this change against my local server with [yarn test-local](https://github.com/all-of-us/workbench/blob/master/e2e/README.md#examples) because this PR won't be covered by the CircleCI tests 
- [ ] If this includes a UI change, I have taken screen recordings or screenshots of the new behavior and notified the PO and UX designer in [Slack](https://pmi-engteam.slack.com/archives/C02MWP2RN5P)
- [ ] If this change impacts deployment safety (e.g. removing/altering APIs which are in use) I have documented these in the description
- [ ] If this includes an API change, I have updated the appropriate Swagger definitions and updated the appropriate API consumers
  * AoU UI
  * [Perf tests](https://github.com/broadinstitute/mcnulty/blob/develop/src/test/scala/services/AoU.scala)
  * [Researcher Directory export](https://github.com/all-of-us/workbench/wiki/Researcher-Directory-(RDR-export))
  * Cron tasks - for Offline*Controllers
  * SumoLogic - for EgressAlert

### CODE REVIEW

**Comment by Peter-Lavigne** [comment]
I tested this by comparing the branch side-by-side with the Test environment on several pages. When the browser font size is set to "Medium," this looks exactly the same.

However, when we change the font size, the site starts to break down in small ways. I've pointed out a few differences in the screenshot below. Notably, some help information cannot be viewed. This is an accessibility concern that you should consider. I'd recommend talking to Moira or Joy about this to figure out our accessibility policies.

I have personally tried using larger fonts (I prefer them) but, sadly, many sites break in similar ways, forcing me to use Medium-sized font.

Screen Shot 2023-01-05 at 10 47 04 AM

**Comment by evrii** [comment]
> I tested this by comparing the branch side-by-side with the Test environment on several pages. When the browser font size is set to "Medium," this looks exactly the same.
> 
> However, when we change the font size, the site starts to break down in small ways. I've pointed out a few differences in the screenshot below. Notably, some help information cannot be viewed. This is an accessibility concern that you should consider. I'd recommend talking to Moira or Joy about this to figure out our accessibility policies.
> 
> I have personally tried using larger fonts (I prefer them) but, sadly, many sites break in similar ways, forcing me to use Medium-sized font.
> 
> Screen Shot 2023-01-05 at 10 47 04 AM

Yeah, I see what you mean. Good catch.

 I think this presents us with an interesting problem. The way that we had our app set up before, we had our font-size set to a fixed pixel size (24px), so updating font-size in the browser would have no effect on the application's font size.

So I would say having our font-size at 100% allows the text to change size but styling breaks down, but keeping it as a fixed pixel value will allow the font size to change but some of the styling will break down. I think that both are accessibility issues. I would say that we keep a fixed value for now.

**Review by Peter-Lavigne — APPROVED** [review]
I agree that's a reasonable fix, approved 👍

**Review by NehaBroad — APPROVED** [review]

**Review by freemabd — APPROVED** [review]
Looks good, thanks.

**Comment by evrii** [comment]
Thanks all!

**Pull request merged**
