### PR TITLE
[RW-6677][risk=no] Fix CDR versions for Puppeteer

### PR DESCRIPTION
**Pull request by calbach**
Missed some references to "Microarray" which should have been removed in #4871 . I didn't dig into the timeline for the original breakage, since issues seemed to start on Saturday and my PR wasn't merged until Monday - either way this should bring things into the expected state.

Also, fix nightly "local" test target to run against local.

### CODE REVIEW

**Comment by calbach** [comment]
Running some local tests now to verify this fix.

**Comment by calbach** [comment]
Nightly tests passed locally. The presubmit puppeteer failures are all expected, because the corresponding CDR config updates haven't been applied in the test environment yet. The only way to have both the presubmit, and post-submit pass would be to add some intermediate transitional CDR versions, or restructure the test.

**Review by aweng98 — APPROVED** [review]
LGTM. 
One question: about `cdr_config_perf.json`, is it correct?

**Comment by aweng98** [comment]
Yes, I was thinking about perf test env setup. I don't think running nightly tests in perf is part of requirement so I don't plan to run nightly tests in perf anytime soon. Thank you for the explanation.

**Pull request merged**
