### PR TITLE
[DT-662][risk=no] Fix name validation for resources

### PR DESCRIPTION
**Pull request by dolbeew**
- Increase char limit for names of non-notebook resources from 80 to 800 chars to avoid db error
- Make UI validation consistent for creating, renaming and duplicating resources
- Fix request for renaming cohort reviews

### CODE REVIEW

**Review by chenchals — COMMENTED** [review]
If a cohort/resource name is 80-chars then they cannot duplicate the cohort. Is that what we want or give option to "change the name of the 'duplicating' resource".  Or atleast give message to rename cohort... The word "Duplicated " is itself 11 chars long (with space) that we append when duplicating resource. 
Also, if I duplicate a workspace - will it automatically check for lengths of other resource-names in the workspace before duplicating?

**Review by freemabd — COMMENTED** [review]
I think a better solution might be to change the column size of name to be bigger:

- Table(cohort) - column(name) - varchar(80) -> varchar(500)
- Table(concept_set) - column(name) - varchar(80) -> varchar(500)
- Table(data_set) - column(name) - varchar(80) -> varchar(500)
- Table(cohort_review) - column(cohort_name) - varchar(80) -> varchar(500)

Another option would be to make the of type `text` instead of `varchar`

This can be done by including a new changelog file for liquibase in db/changelog

**Comment by chenchals** [comment]
> I think a better solution might be to change the column size of name to be bigger:
> 
> * Table(cohort) - column(name) - varchar(80) -> varchar(1500)
> * Table(concept_set) - column(name) - varchar(80) -> varchar(1500)
> * Table(data_set) - column(name) - varchar(80) -> varchar(1500)
> * Table(cohort_review) - column(cohort_name) - varchar(80) -> varchar(1500)
> 
> Another option would be to make the of type `text` instead of `varchar`
> 
> This can be done by including a new changelog file for liquibase in db/changelog
> 
> Example: `<changeSet author="liquibase" id="sample"> <modifyDataType columnName="name" newDataType="varchar(1500)" tableName="cohort"/> </changeSet>`

Yes, that would be better. And going forward, may be restrict the "length" of resource name - during creation of resource with a pop-up?

**Review by freemabd — APPROVED** [review]
Thanks

**Pull request merged**
