### PR TITLE
[RW-7326][risk=no] Show security suspended UX for runtime icon in sidebar

### PR DESCRIPTION
**Pull request by calbach**
image

### CODE REVIEW

**Comment by calbach** [comment]
@yonghaoy ptal

**Review by yonghaoy — APPROVED** [review]

**Comment by yonghaoy** [comment]
what happened if I click "terminal" icon? Or open a notebook?

**Comment by calbach** [comment]
Opening a notebook is covered by https://github.com/all-of-us/workbench/pull/5834 .

Terminal is a good point, it should get this same treatment. Will update.

**Comment by calbach** [comment]
Actually, this is probably OK as-is. When runtime is security suspended, it will be stopped. Terminal should be disabled. If you try to load the terminal, you'll get the behavior on https://github.com/all-of-us/workbench/pull/5834, since it uses the same page.

**Comment by calbach** [comment]
I tried this out last night and decided it would be more consistent to disable the terminal button

**Pull request merged**
