### PR TITLE
[DT-665][risk=no] Update test env url refs

### PR DESCRIPTION
**Pull request by dolbeew**
Update url references in test for custom domain:
- Change frontend urls from `https://all-of-us-workbench-test.appspot.com` to `https://test.fake-research-aou.org`
- Change api urls from `https://api-dot-all-of-us-workbench-test.appspot.com` to `https://api.test.fake-research-aou.org`

### CODE REVIEW

**Review by freemabd — APPROVED** [review]
Thanks.

**Review by yonghaoy — APPROVED** [review]

**Comment by yonghaoy** [comment]
There might be few other followups.
Please check this epic see anything else for test env: https://precisionmedicineinitiative.atlassian.net/browse/RW-8918

**Comment by dolbeew** [comment]
@yonghaoy That epic is for staging env and looks like all the tickets are done. Is there a similar epic for test env? At first glance I didn't see one

**Comment by yonghaoy** [comment]
> @yonghaoy That epic is for staging env and looks like all the tickets are done. Is there a similar epic for test env? At first glance I didn't see one

We do not have epic for test. That epci is an example to list things we need to do in generate when chaning domain.
We might need to do similar things for test env. 
Few tickets might not needed until we deprecated the old API hostname (and I assume we are not doing that, right?).
The ticket we might need to do is the ReCaptcha change.

**Comment by dolbeew** [comment]
Ok, I'll take a look at ReCaptcha and the other tickets.

We are planning on either removing the UI `https://all-of-us-workbench-test.appspot.com` url or redirecting traffic to the new url but I don't think we need to remove the api url yet.

**Comment by dolbeew** [comment]
@yonghaoy I added the new domain to the test ReCaptcha project and will remove the old one once we disable it. Is that the only change we need for ReCaptcha?
Screenshot 2024-01-10 at 9 14 33 AM

**Comment by yonghaoy** [comment]
@dolbeew we can not remove the old domain now, I remember there are some issues for test env that blocks us from migrating. 
One issue I just remembered is deploy a personal version to test things. Would your PR affect that case?

**Pull request merged**
