### PR TITLE
[RW-638] [RW-639] getting copy, font and wraps right

### PR DESCRIPTION
**Pull request by UrsaStutsman**

### CODE REVIEW

**Comment by UrsaStutsman** [comment]
Still waiting for Lou to sign off on. Once he has, also will give Fritz a pass. Screenshot here:
screen shot 2018-05-11 at 10 43 20 am

**Comment by blrubenstein** [comment]
Tagging @lstrano-broad and @fknabe

**Comment by UrsaStutsman** [comment]
@lstrano-broad I pinged you on slack with screenshots with a revision that unwraps those lines

**Comment by UrsaStutsman** [comment]
screen shot 2018-05-11 at 12 41 54 pm
screen shot 2018-05-11 at 12 42 05 pm
screen shot 2018-05-11 at 12 42 48 pm

**Comment by fknabe** [comment]
LGTM

**Pull request merged**
