### PR TITLE
Add disable to revoke and grant access

### PR DESCRIPTION
**Pull request by blrubenstein**

### CODE REVIEW

**Comment by danqrodney** [comment]
(If not, do we still want the endpoint to disable a user?)

**Comment by blrubenstein** [comment]
This basically turns what was previously removing or adding people to the auth domain into a blanket disable. (I think we just need the one endpoint, since removing them from the auth domain is actually a more complete disable than our disable flag is.)

**Comment by danqrodney** [comment]
OK. Should we remove the other endpoint then?

**Comment by blrubenstein** [comment]
Yeah, I'll remove that and the disable account button from the UI.

**Pull request merged**
