### PR TITLE
[risk=no] Delete apparently unused generate-cdr CSVs

### PR DESCRIPTION
**Pull request by calbach**
Please advise if any of the other files around here can be removed as well: https://github.com/all-of-us/workbench/tree/master/api/db-cdr/generate-cdr/csv

### CODE REVIEW

**Comment by calbach** [comment]
Sure - but specifically this achilles_results file is not necessary - right?

**Comment by freemabd1** [comment]
I faintly remember @biopete saying this is true, but he should confirm this.

**Comment by biopete** [comment]
Yeah. That was an accident getting put in there.  The new pr we merge will delete it.

**Comment by calbach** [comment]
Dropping then

**Pull request closed without merging**
