### PR TITLE
[RW-1422][Risk=low] Change font to montserrat

### PR DESCRIPTION
**Pull request by blrubenstein**

### CODE REVIEW

**Comment by calbach** [comment]
Do you mind bringing up a demo server? We also are using Gotham HTF pretty widely but most of Lou's mocks now have Montserrat instead.

**Comment by blrubenstein** [comment]
Yeah, I can bring one up. Will do so when I have a moment.

**Comment by calbach** [comment]
Also, wasn't Gotham HTF included in that cloudtypography link? If so I would expect all of those font rules to break

**Comment by blrubenstein** [comment]
Yes, but this should remove all gotham htf.

**Comment by blrubenstein** [comment]
I couldn't find any instances of `Gotham` in the UI directory after this PR.

**Comment by calbach** [comment]
Ah - the others I saw were in public-ui (which I think probably never worked).

Also one more in the welcome email (which I think never worked since we didn't load the CSS URL) - probably can just remove that one entirely

**Comment by blrubenstein** [comment]
Added email references as well, I want to add a separate ticket for public-ui

**Pull request merged**
