### PR TITLE
[RW-4498][risk=no] supply not-really-optional name param

### PR DESCRIPTION
**Pull request by jaycarlton**
We were getting warnings every minute b/c the name param was missing. Either make it required or pipe down already, guys.

---
**PR checklist**

- [ ] This PR meets the Acceptance Criteria in the JIRA story
- [ ] The JIRA story has been moved to Dev Review
- [ ] This PR includes appropriate unit tests
- [ ] I have run and tested this change locally
- [ ] If this includes an API change, I have updated the appropriate Swagger definitions and notified API consumers
- [ ] If this includes a new feature flag, I have created and linked new JIRA tickets to (a) turn on the feature flag and (b) remove it later

### CODE REVIEW

**Comment by jaycarlton** [comment]
What would you like me to put in it?

**Comment by als364** [comment]
What is its purpose?

**Comment by jaycarlton** [comment]
That will have to remain a mystery for now. Looks like it was supposed to be hidden and got caught in my git net somehow.

**Comment by jaycarlton** [comment]
I have to hit Ctrl+C a bunch more times now to stop `dev-up`, and I bet I killed it too hard or suddenly or something.

**Pull request merged**
