### PR TITLE
[no ticket][risk=no] buildfix for updated authority

### PR DESCRIPTION
**Pull request by jaycarlton**
Description:

---
**PR checklist**

- [ ] This PR meets the Acceptance Criteria in the JIRA story
- [ ] The JIRA story has been moved to Dev Review
- [ ] This PR includes appropriate unit tests
- [ ] I have run and tested this change locally
- [ ] I have run the E2E tests on ths change against my local UI + API server with `yarn test-local`
- [ ] If this includes a UI change, I have taken screen recordings or screenshots of the new behavior and notified the PO and UX designer
- [ ] If this includes an API change, I have updated the appropriate Swagger definitions and notified API consumers
- [ ] If this includes a new feature flag, I have created and linked new JIRA tickets to (a) turn on the feature flag and (b) remove it later

### CODE REVIEW

**Comment by calbach** [comment]
This seems like a case of the "skip UI tests" logic gone wrong. We should ensure that changes to the Swagger yaml files are triggering the UI build.

**Comment by calbach** [comment]
(not in this PR, obviously)

**Comment by aweng98** [comment]
Merged PR that broke test had zero change in `ui` folder. It explains why UI tests were skipped.
https://github.com/all-of-us/workbench/pull/3624

**Comment by jaycarlton** [comment]
It's my fault. The e2e was running, and there were errors, but I assumed they weren't my fault since I was only working with endpoints that aren't in use yet.

But yes, any swagger file change should run everything.

**Pull request merged**
