### PR TITLE
[RW-862][RW-863][risk=no] - Adding help tips to workspace about and notebook list page

### PR DESCRIPTION
**Pull request by UrsaStutsman**
Replace this this template with your PR description.
Please remember to keep in mind the security levels outlined in [CONTRIBUTING.md](CONTRIBUTING.md) and to 
include a risk tag of the form `[risk=no|low|moderate|severe]` in the PR title

* **no**: None 
* **low**: Low chance of potential impact to, or exposure of patient data
* **moderate**: Moderate chance of potential impact to, or exposure of patient data
* **severe**: Severe chance of potential impact to, or exposure of patient data

Please also:

* Get thumbs from reviewer(s)
* Verify all tests go green, including CI tests

### CODE REVIEW

**Comment by UrsaStutsman** [comment]
@lstrano-broad  Screenshots of help tips
screen shot 2018-07-03 at 10 12 34 am
screen shot 2018-07-03 at 10 13 01 am
screen shot 2018-07-03 at 10 13 14 am

**Comment by lstrano-broad** [comment]
Once user creates a Notebooks or Cohort the Help Tip will not be shown

**Comment by rushtong** [comment]
@lstrano-broad - That is not the case on the notebooks tab. On that tab, the help tip remains even if there are 10 notebooks. I believe that was a decision you and Ursa came to.

**Comment by lstrano-broad** [comment]
Second screen show a couple of notebooks created - doubtful that a user will create multiple notebooks without creating 1 cohort - so I'm ok with leaving the tip logic as is. In user testing we can gather learnings on this.

**Comment by rushtong** [comment]
👍 Thumbed with Lou's approval of the notebook logic.

**Comment by lstrano-broad** [comment]
You are correct Greg - but referring back to my previous reply, don't think we'll run into a case where there are multiple notebooks and no cohorts. Could be wrong.

**Pull request merged**
