### PR TITLE
Getting rid of StatusApi binding which wasn't working for some reason.

### PR DESCRIPTION
**Pull request by danqrodney**
(We can just make a new one on each request until we work this out.)

### CODE REVIEW

**Comment by calbach** [comment]
Uh oh. Could you elaborate on "wasn't working for some reason"?

@blrubenstein

**Comment by blrubenstein** [comment]
This is something that I didn't notice until after I started working on the UI and got strange errors. Dan managed to figure out that spring just doesn't like the name `statusApi`.

**Comment by danqrodney** [comment]
To clarify: I didn't figure out anything in particular about this. (I didn't try renaming this to some other named bean, for example.) I just knew an easy fix is not getting Spring involved at all. :)

Somebody should look into what exactly is going on here.

**Comment by danqrodney** [comment]
Also: this highlights the need for us to have tests which run dev-up and verify everything comes up as intended. I'll bring this up at tomorrow's meeting.

**Comment by calbach** [comment]
Weird, I had definitely validated a fix locally on Friday, but I may have changed the string to `"statusApi"` before mailing the PR, so the specific string may be the issue. Indeed I just changed "statusApi" -> "foo" locally and it worked..

Having a test which verifies that the server actually starts would definitely be a good idea.

**Pull request merged**
